name: Publish Commands
on: [push]


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install modules
      run: npm ci
    - name: remove watch flag
      run: npm run removeWatch
    - name: tsc
      run: ./node_modules/typescript/bin/tsc 
    - name: Run publish
      run: npm run deploy

