name: Publish Commands
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install modules
      run: npm ci
    - name: Typescript compiler
      uses: iCrawl/action-tsc@v1
      with:
        watch: false
    - name: Run publish
      run: npm run deploy
