name: Publish Commands
on: [push]

env:
  bestFood: potato

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install modules
      run: npm ci
    - name: deploy commands
      run: npm run deploy
