name: Publish Commands
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Setup TypeScript
      uses: Tyler887/TypeScript-GitHub-Actions@1.0
    - name: Install modules
      run: npm ci
    - name: tsc
      run: tsc --watch=false
    - name: Run publish
      run: npm run deploy
